openapi: '3.0.3'
info:
  title: Praktikum REST API
  version: '1.0'
servers:
  - url: https://localhost:3000

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        age:
          type: integer
        createdAt:
          type: string
        updatedAt:
          type: string

paths:
  /users:
    get:
      description: Endpoint untuk mendapatkan semua data user
      responses:
        '200':
          description: Berhasil
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/User"
        '500':
          description: Server Gagal
        '403':
          description: Tidak diizinkan

  /users/{id}:
    get:
      description: Endpoint untuk mendapatkan data user berdasarkan ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Berhasil
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/User'
        '500':
          description: Server Gagal
        '403':
          description: Tidak diizinkan

    delete:
      description: Endpoint untuk menghapus data user berdasarkan ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Berhasil
        '500':
          description: Server Gagal
        '403':
          description: Tidak diizinkan

    put:
      description: Endpoint untuk mengubah data user berdasarkan ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                age:
                  type: integer
      responses:
        '200':
          description: Berhasil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '500':
          description: Server Gagal
        '403':
          description: Tidak diizinkan
